dependencies = { }
dev-dependencies = { }
dev-addresses = { }

[package]
name = "ika"
edition = "2024"
license = "BSD-3-Clause-Clear"
authors = [ "dWallet Labs, Ltd. <dev@dwalletlabs.com>" ]
published-at = "0xf3c62a30583318ae542f6b9de61a48cb6c558001873bbbdca988224727003a62"

[addresses]
ika = "0xf3c62a30583318ae542f6b9de61a48cb6c558001873bbbdca988224727003a62"
