[package]
name = "ika_dwallet_2pc_mpc"
edition = "2024"
license = "BSD-3-Clause-Clear"
authors = ["dWallet Labs, Ltd. <dev@dwalletlabs.com>"]
published-at = "0x4bd485cc90febffe238834cba1c62cce297cd4c5594bdbc596860f4c712aa0e4"

[dependencies]
ika = { local = "../ika" }
ika_common = { local = "../ika_common" }

[addresses]
ika_dwallet_2pc_mpc = "0x4bd485cc90febffe238834cba1c62cce297cd4c5594bdbc596860f4c712aa0e4"

[dev-dependencies]

[dev-addresses]